version: '3'
services:

  ml_api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./:/app
    ports:
      - "8000:8000"
      
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      
  grafana:
    hostname: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"